#!/usr/bin/with-contenv bash

if [ -f "/hugo/hugo.deb" ]; then
    echo "**** installing hugo from deb ****"

    dpkg -i /hugo/hugo.deb
    rm -rf /hugo

    echo "**** done installing hugo ****"
else
    echo "**** Hugo already installed ****"
fi